config/routes.rb
Rails.application.routes.draw do
  resources :questions, only: [:index, :show]

  resources :disciplines, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/discipline.rb
class Discipline < ApplicationRecord
  has_many :questions

  validates :name, presence: true
  
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :discipline
  has_many :question_access
  validates :statement, :text, :answer, presence: true

  counter_culture :discipline , column_name: 'questions_daily_access', delta_column: 'daily_access'
end

app/models/question_access.rb
class QuestionAccess < ApplicationRecord
  belongs_to :question
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  before_action :set_discipline, only: [:show]

  # GET /disciplines
  # GET /disciplines.json
  def index
    @disciplines = Discipline.order(questions_daily_access: :desc)
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline
      @discipline = Discipline.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def discipline_params
      params.fetch(:discipline, {})
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show]

  # GET /questions
  # GET /questions.json
  def index
    @q = QuestionAccess.ransack(params[:q])
    @more_accessed_ids = @q.result(distinct: true)
                           .includes(:question)
                           .joins(:question)
                           .order('sum_times_accessed DESC')
                           .group('questions.id')
                           .sum('times_accessed')

    @questions = Question.find(@more_accessed_ids.keys)
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:statement, :text, :answer, :daily_access, :discipline_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/disciplines/_form.html.erb
<%= form_with(model: discipline, local: true) do |form| %>
  <% if discipline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discipline.errors.count, "error") %> prohibited this discipline from being saved:</h2>

      <ul>
      <% discipline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/disciplines/edit.html.erb
<h1>Editing Discipline</h1>

<%= render 'form', discipline: @discipline %>

<%= link_to 'Show', @discipline %> |
<%= link_to 'Back', disciplines_path %>

app/views/disciplines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Disciplines</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @disciplines.each do |discipline| %>
      <tr>
        <td><%= link_to 'Show', discipline %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/disciplines/new.html.erb
<h1>New Discipline</h1>

<%= render 'form', discipline: @discipline %>

<%= link_to 'Back', disciplines_path %>

app/views/disciplines/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', disciplines_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuestionsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :statement %>
    <%= form.text_field :statement %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_field :answer %>
  </div>

  <div class="field">
    <%= form.label :daily_access %>
    <%= form.number_field :daily_access %>
  </div>

  <div class="field">
    <%= form.label :discipline_id %>
    <%= form.text_field :discipline_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Statement</th>
      <th>Text</th>
      <th>Answer</th>
      <th>Daily access</th>
      <th>Discipline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.statement %></td>
        <td><%= question.text %></td>
        <td><%= question.answer %></td>
        <td><%= question.daily_access %></td>
        <td><%= question.discipline %></td>
        <td><%= link_to 'Show', question %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Statement:</strong>
  <%= @question.statement %>
</p>

<p>
  <strong>Text:</strong>
  <%= @question.text %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @question.answer %>
</p>

<p>
  <strong>Daily access:</strong>
  <%= @question.daily_access %>
</p>

<p>
  <strong>Discipline:</strong>
  <%= @question.discipline %>
</p>

<%= link_to 'Back', questions_path %>